const realStaticRoutes = [
  '/',
  '/404',
  '/abertura-de-empresa',
  '/abertura-empresa-sc',
  '/autor/[slug]',
  '/blog/[slug]',
  '/blog/index',
  '/calculadora-fator-r',
  '/calendario-fiscal-2026',
  '/como-abrir-empresa-em-blumenau',
  '/consultoria-e-planejamento-tributario',
  '/contabilidade-em-balneario-camboriu',
  '/contabilidade-em-blumenau',
  '/contabilidade-em-bombas',
  '/contabilidade-em-bombinhas',
  '/contabilidade-em-florianopolis',
  '/contabilidade-em-gaspar',
  '/contabilidade-em-indaial',
  '/contabilidade-em-itajai',
  '/contabilidade-em-pomerode',
  '/contabilidade-em-porto-belo',
  '/contabilidade-em-timbo',
  '/contabilidade-garcia-blumenau',
  '/contabilidade-para-clinicas-medicas',
  '/contabilidade-para-construcao-civil',
  '/contabilidade-para-empresas',
  '/contabilidade-para-empresas-de-ti',
  '/contabilidade-para-importacao-sc',
  '/contabilidade-para-industria',
  '/contabilidade-para-pessoa-fisica',
  '/contabilidade-para-transportadoras',
  '/contabilidade-velha-blumenau',
  '/contabilidade-vila-nova-blumenau',
  '/fale-conosco',
  '/gestao-contabil',
  '/gestao-fiscal-e-tributaria',
  '/gestao-pessoal',
  '/imposto-de-renda',
  '/index',
  '/mapa-do-site',
  '/migrar-de-mei-para-ltda',
  '/politica-de-privacidade',
  '/reforma-tributaria',
  '/regimes-tributarios',
  '/retirada-de-socios',
  '/segmentos',
  '/seguranca-dos-dados',
  '/simples-nacional',
  '/simulador-regime-tributario',
  '/sobre',
  '/termos-de-uso',
  '/trabalhe-conosco',
  '/transformar-mei-em-ltda'
];

// Referenced static links from astro files
const referencedStaticLinks = [
  '/',
  '/abertura-de-empresa',
  '/abertura-empresa-sc',
  '/blog',
  '/calculadora-fator-r',
  '/calendario-fiscal-2026',
  '/como-abrir-empresa-em-blumenau',
  '/consultoria-e-planejamento-tributario',
  '/contabilidade-em-balneario-camboriu',
  '/contabilidade-em-blumenau',
  '/contabilidade-em-bombas',
  '/contabilidade-em-bombinhas',
  '/contabilidade-em-florianopolis',
  '/contabilidade-em-gaspar',
  '/contabilidade-em-indaial',
  '/contabilidade-em-itajai',
  '/contabilidade-em-pomerode',
  '/contabilidade-em-porto-belo',
  '/contabilidade-em-timbo',
  '/contabilidade-para-clinicas-medicas',
  '/contabilidade-para-empresas',
  '/contabilidade-para-importacao-sc',
  '/contabilidade-para-industria',
  '/contabilidade-para-pessoa-fisica',
  '/fale-conosco',
  '/fale-conosco?assunto=troca-de-contador',
  '/gestao-contabil',
  '/gestao-fiscal-e-tributaria',
  '/gestao-pessoal',
  '/imposto-de-renda',
  '/mapa-do-site',
  '/migrar-de-mei-para-ltda',
  '/politica-de-privacidade',
  '/reforma-tributaria',
  '/retirada-de-socios',
  '/seguranca-dos-dados',
  '/simples-nacional',
  '/simulador-regime-tributario',
  '/sobre',
  '/termos-de-uso',
  '/trabalhe-conosco'
];

// Also from markdown files
const markdownStaticLinks = [
  '/abertura-de-empresa',
  '/fale-conosco',
  '/fale-conosco',
  '/como-abrir-empresa-em-blumenau',
  '/abertura-de-empresa',
  '/fale-conosco',
  '/como-abrir-empresa-em-blumenau',
  '/abertura-de-empresa',
  '/regimes-tributarios',
  '/simulador-regime-tributario',
  '/blog/cnae-como-escolher-o-certo-e-por-que-errar-sai-caro',
  '/fale-conosco',
  '/como-abrir-empresa-em-blumenau',
  '/abertura-de-empresa',
  '/simples-nacional',
  '/blog/simples-nacional-2026-tabelas-e-limites',
  '/fale-conosco',
  '/como-abrir-empresa-em-blumenau',
  '/abertura-de-empresa',
  '/fale-conosco',
  '/fale-conosco',
  '/como-abrir-empresa-em-blumenau',
  '/abertura-de-empresa',
  '/consultoria-e-planejamento-tributario',
  '/regimes-tributarios',
  '/fale-conosco',
  '/como-abrir-empresa-em-blumenau',
  '/abertura-de-empresa',
  '/fale-conosco',
  '/como-abrir-empresa-em-blumenau',
  '/fale-conosco',
  '/abertura-de-empresa',
  '/consultoria-e-planejamento-tributario',
  '/reforma-tributaria',
  '/fale-conosco',
  '/blog/split-payment-reforma-tributaria-o-que-muda-para-sua-empresa',
  '/fale-conosco',
  '/abertura-de-empresa',
  '/como-abrir-empresa-em-blumenau',
  '/fale-conosco',
  '/como-abrir-empresa-em-blumenau',
  '/abertura-de-empresa',
  '/fale-conosco',
  '/como-abrir-empresa-em-blumenau',
  '/fale-conosco',
  '/fale-conosco',
  '/como-abrir-empresa-em-blumenau',
  '/abertura-de-empresa',
  '/regimes-tributarios',
  '/fale-conosco',
  '/fale-conosco',
  '/fale-conosco',
  '/como-abrir-empresa-em-blumenau',
  '/abertura-de-empresa',
  '/consultoria-e-planejamento-tributario',
  '/reforma-tributaria',
  '/fale-conosco',
  '/fale-conosco',
  '/como-abrir-empresa-em-blumenau',
  '/abertura-de-empresa',
  '/fale-conosco',
  '/fale-conosco',
  '/como-abrir-empresa-em-blumenau',
  '/abertura-de-empresa',
  '/regimes-tributarios',
  '/fale-conosco',
];

const allReferenced = [...referencedStaticLinks, ...markdownStaticLinks];
const uniqueReferenced = [...new Set(allReferenced)];

console.log('=== BROKEN STATIC LINKS ===');
for (const link of uniqueReferenced) {
  // Skip query params and assets
  if (link.includes('?') || link.startsWith('/assets/') || link.startsWith('/fonts/') || link.startsWith('/bi/') || link.startsWith('/_astro/')) continue;
  // Skip dynamic routes
  if (link.includes('[slug]')) continue;
  if (!realStaticRoutes.includes(link)) {
    console.log('BROKEN: ' + link);
  }
}

console.log('\n=== VALID STATIC LINKS ===');
for (const link of uniqueReferenced) {
  if (link.includes('?') || link.startsWith('/assets/') || link.startsWith('/fonts/') || link.startsWith('/bi/') || link.startsWith('/_astro/')) continue;
  if (link.includes('[slug]')) continue;
  if (realStaticRoutes.includes(link)) {
    console.log('OK: ' + link);
  }
}
