const fs = require('fs');

// Real blog slugs (from src/content/blog/*.md)
const realBlogSlugs = [
  'abertura-de-empresa-blumenau-passo-a-passo-completo-2026',
  'abertura-de-empresa-em-santa-catarina-passo-a-passo-2026',
  'abertura-empresa-indaial-guia-2026',
  'alvara-funcionamento-blumenau-guia',
  'bloco-k-sped-fiscal-industria-guia',
  'bpo-financeiro-organizacao-caixa-pequenas-empresas',
  'certificado-digital-a1-vs-a3-qual-escolher',
  'cnae-como-escolher-o-certo-e-por-que-errar-sai-caro',
  'cnpj-alfanumerico-2026-o-que-muda-para-sua-empresa',
  'como-escolher-contador-blumenau-guia-2026',
  'como-regularizar-empresa-com-debitos-na-receita-federal',
  'contabilidade-gerencial-use-numeros-para-decidir',
  'contabilidade-industria-textil-blumenau-sc',
  'contabilidade-para-advogados-blumenau',
  'contabilidade-para-condominios-blumenau',
  'contabilidade-para-construcao-civil-blumenau',
  'contabilidade-para-dentistas-blumenau',
  'contabilidade-para-empresas-de-tecnologia-blumenau-2026',
  'contabilidade-para-engenheiros-arquitetos-blumenau',
  'contabilidade-para-industria-blumenau',
  'contabilidade-para-medicos-clinicas-blumenau',
  'contabilidade-para-pousadas-turismo-litoral-sc',
  'contabilidade-para-profissionais-liberais-o-que-voce-precisa-saber',
  'contabilidade-para-psicologia-blumenau',
  'contabilidade-para-restaurantes-blumenau',
  'contador-gaspar-como-escolher',
  'credito-icms-diesel-transportadoras-santa-catarina-2026',
  'das-atrasado-simples-nacional-como-regularizar',
  'desenquadramento-mei-excesso-receita-2026',
  'desenquadramento-mei-por-faturamento-2026',
  'desenquadramento-mei-retroativo-2026',
  'desoneracao-da-folha-2026-o-que-muda-com-a-reoneracao',
  'distribuicao-de-lucros-2026-como-fazer-certo-e-pagar-menos-imposto',
  'domicilio-eletronico-trabalhista-det-riscos-notificacoes',
  'equiparacao-hospitalar-clinicas-medicas-sc-tema-328-stj',
  'esocial-2026-o-que-mudou-e-o-que-esperar',
  'exportacao-de-software-servicos-ti-impostos-2026',
  'fator-r-no-simples-nacional-guia-reduzir-impostos',
  'fator-r-simples-nacional-como-calcular',
  'fluxo-de-caixa-guia-para-empresarios',
  'holding-familiar-vale-a-pena-para-pequenos-empresarios',
  'holding-patrimonial-em-sc-como-proteger-bens-e-economizar-impostos',
  'impostos-indaial-empresas-vale',
  'incentivos-fiscais-blumenau-pagar-menos-imposto',
  'inss-de-obra-como-calcular-e-regularizar-no-sero-2026',
  'irpf-2026-blumenau-como-declarar-dicas-escritorio',
  'irpf-2026-como-declarar-imposto-de-renda',
  'iss-em-blumenau-aliquotas-por-servico-e-como-calcular',
  'lei-15377-2026-vacinacao-empresas-obrigacao-comunicar',
  'lucro-presumido-vs-lucro-real',
  'malha-fina-pj-2026-pix-faturamento',
  'mei-2026-guia-completo-microempreendedor-individual',
  'mei-estourou-o-faturamento-o-que-fazer-agora',
  'melhor-contabilidade-blumenau-como-escolher-2026',
  'migrar-de-mei-para-ltda-guia-completo-2026',
  'nfs-e-blumenau-como-emitir',
  'nota-fiscal-de-servicos-como-emitir-corretamente',
  'notificacao-simples-nacional-termo-exclusao-2026',
  'novos-impostos-nota-fiscal-ibs-cbs-2026',
  'nr-1-riscos-psicossociais-2026-fiscalizacao-obrigacoes',
  'planejamento-tributario-2027-agosto-decisivo',
  'planejamento-tributario-como-pagar-menos-imposto-legalmente',
  'pro-labore-e-dividendos-2026',
  'quanto-custa-abrir-empresa-em-blumenau-custos-e-taxas-2026',
  'quanto-custa-um-contador-o-que-voce-deveria-estar-pagando',
  'reforma-tributaria-2026',
  'reforma-tributaria-atualizacao-erp-sistemas-2026',
  'regime-hibrido-simples-nacional-prazo-setembro-2026',
  'regimes-tributarios-blumenau-resumo',
  'regularizacao-obra-cno-sero-guia',
  'separar-pessoa-fisica-de-juridica-o-erro-que-mata-pequenos-negocios',
  'simples-nacional-2026-tabelas-e-limites',
  'split-payment-reforma-tributaria-o-que-muda-para-sua-empresa',
  'transicao-lucro-presumido-para-lucro-real-sc',
  'troca-de-contador-quando-vale-e-como-fazer-sem-susto',
  'ttd-409-santa-catarina-como-funciona-guia-2026',
  'ttd-410-sc-credito-presumido-importacao'
];

// Referenced blog links (from astro files + markdown)
const referencedBlogLinks = [
  '/blog/abertura-de-empresa-blumenau-passo-a-passo-completo-2026',
  '/blog/abertura-de-empresa-em-santa-catarina-passo-a-passo-2026',
  '/blog/bloco-k-sped-fiscal-como-evitar-multas',
  '/blog/cnae-como-escolher-o-certo-e-por-que-errar-sai-caro',
  '/blog/como-abrir-empresa-em-blumenau',
  '/blog/contabilidade-para-industria-blumenau',
  '/blog/contabilidade-para-medicos-clinicas-blumenau',
  '/blog/contabilidade-para-profissionais-liberais-o-que-voce-precisa-saber',
  '/blog/credito-icms-diesel-transportadoras-santa-catarina-2026',
  '/blog/creditos-icms-ipi-pis-cofins-industria',
  '/blog/cte-mde-frete-transportadoras-como-evitar-multas',
  '/blog/das-atrasado-simples-nacional-como-regularizar',
  '/blog/desenquadramento-mei-excesso-receita-2026',
  '/blog/desenquadramento-mei-por-faturamento-2026',
  '/blog/desenquadramento-mei-retroativo-2026',
  '/blog/desoneracao-da-folha-2026-o-que-muda-com-a-reoneracao',
  '/blog/distribuicao-de-lucros-2026-como-fazer-certo-e-pagar-menos-imposto',
  '/blog/esocial-2026-o-que-mudou-e-o-que-esperar',
  '/blog/exportacao-de-software-servicos-ti-impostos-2026',
  '/blog/fator-r-simples-nacional-como-calcular',
  '/blog/fator-r-simples-nacional-contabilidade-ti',
  '/blog/holding-familiar-vale-a-pena-para-pequenos-empresarios',
  '/blog/incentivos-fiscais-blumenau-pagar-menos-imposto',
  '/blog/irpf-2026-como-declarar-imposto-de-renda',
  '/blog/lei-do-bem-empresas-tecnologia-inovacao',
  '/blog/lucro-presumido-vs-lucro-real',
  '/blog/mei-2026-guia-completo-microempreendedor-individual',
  '/blog/mei-estourou-o-faturamento-o-que-fazer-agora',
  '/blog/migrar-de-mei-para-ltda-guia-completo-2026',
  '/blog/planejamento-tributario-como-pagar-menos-imposto-legalmente',
  '/blog/pro-labore-e-dividendos-2026',
  '/blog/quanto-custa-abrir-empresa-em-blumenau-custos-e-taxas-2026',
  '/blog/reforma-tributaria-2026',
  '/blog/reforma-tributaria-atualizacao-erp-sistemas-2026',
  '/blog/simples-nacional-2026-tabelas-e-limites',
  '/blog/simples-nacional-lucro-real-transportadora-frota-2026',
  '/blog/split-payment-reforma-tributaria-o-que-muda-para-sua-empresa',
  '/blog/abertura-de-empresa-em-santa-catarina-passo-a-passo-2026',
  '/blog/quanto-custa-abrir-empresa-em-blumenau-custos-e-taxas-2026',
  '/blog/quanto-custa-abrir-empresa-em-blumenau-custos-e-taxas-2026',
  '/blog/cnae-como-escolher-o-certo-e-por-que-errar-sai-caro',
  '/blog/cnae-como-escolher-o-certo-e-por-que-errar-sai-caro',
  '/blog/simples-nacional-2026-tabelas-e-limites',
  '/blog/mei-2026-guia-completo-microempreendedor-individual',
  '/blog/como-escolher-contador-blumenau-guia-2026',
  '/blog/abertura-de-empresa-blumenau-passo-a-passo-completo-2026',
  '/blog/incentivos-fiscais-blumenau-pagar-menos-imposto',
  '/blog/simples-nacional-2026-tabelas-e-limites',
  '/blog/troca-de-contador-quando-vale-e-como-fazer-sem-susto',
  '/blog/fluxo-de-caixa-guia-para-empresarios',
  '/blog/distribuicao-de-lucros-2026-como-fazer-certo-e-pagar-menos-imposto',
  '/blog/separar-pessoa-fisica-de-juridica-o-erro-que-mata-pequenos-negocios',
  '/blog/fator-r-simples-nacional-como-calcular',
  '/blog/holding-familiar-vale-a-pena-para-pequenos-empresarios',
  '/blog/reforma-tributaria-2026',
  '/blog/reforma-tributaria-2026',
  '/blog/split-payment-reforma-tributaria-o-que-muda-para-sua-empresa',
  '/blog/fale-conosco',
  '/blog/fator-r-simples-nacional-contabilidade-ti',
  '/blog/lei-do-bem-empresas-tecnologia-inovacao',
  '/blog/cte-mde-frete-transportadoras-como-evitar-multas',
  '/blog/simples-nacional-lucro-real-transportadora-frota-2026',
  '/blog/bloco-k-sped-fiscal-industria-guia',
  '/blog/contabilidade-industria-textil-blumenau-sc',
  '/blog/abertura-de-empresa-em-santa-catarina-passo-a-passo-2026',
  '/blog/cnae-como-escolher-o-certo-e-por-que-errar-sai-caro',
  '/blog/simples-nacional-2026-tabelas-e-limites',
  '/blog/mei-2026-guia-completo-microempreendedor-individual',
  '/blog/desenquadramento-mei-por-faturamento-2026',
  '/blog/desenquadramento-mei-retroativo-2026',
  '/blog/desenquadramento-mei-excesso-receita-2026',
  '/blog/mei-estourou-o-faturamento-o-que-fazer-agora',
  '/blog/migrar-de-mei-para-ltda-guia-completo-2026',
  '/blog/desenquadramento-mei-retroativo-2026',
  '/blog/desenquadramento-mei-por-faturamento-2026',
  '/blog/desenquadramento-mei-excesso-receita-2026',
  '/blog/mei-estourou-o-faturamento-o-que-fazer-agora',
  '/blog/migrar-de-mei-para-ltda-guia-completo-2026',
  '/blog/guia-completo-para-abrir-empresa-em-blumenau',
  '/blog/reforma-tributaria-2026',
  '/blog/reforma-tributaria-2026',
  '/blog/fator-r-simples-nacional-contabilidade-ti',
  '/blog/lei-do-bem-empresas-tecnologia-inovacao'
];

// From markdown files
const markdownReferenced = [
  '/blog/abertura-de-empresa-blumenau-passo-a-passo-completo-2026',
  '/blog/cnae-como-escolher-o-certo-e-por-que-errar-sai-caro',
  '/blog/mei-estourou-o-faturamento-o-que-fazer-agora',
  '/blog/quanto-custa-abrir-empresa-em-blumenau-custos-e-taxas-2026',
  '/blog/quanto-custa-abrir-empresa-em-blumenau-custos-e-taxas-2026',
  '/blog/cnae-como-escolher-o-certo-e-por-que-errar-sai-caro',
  '/blog/simples-nacional-2026-tabelas-e-limites',
  '/blog/mei-2026-guia-completo-microempreendedor-individual',
  '/blog/como-escolher-contador-blumenau-guia-2026',
  '/blog/abertura-de-empresa-blumenau-passo-a-passo-completo-2026',
  '/blog/incentivos-fiscais-blumenau-pagar-menos-imposto',
  '/blog/simples-nacional-2026-tabelas-e-limites',
  '/blog/troca-de-contador-quando-vale-e-como-fazer-sem-susto',
  '/blog/fluxo-de-caixa-guia-para-empresarios',
  '/blog/distribuicao-de-lucros-2026-como-fazer-certo-e-pagar-menos-imposto',
  '/blog/separar-pessoa-fisica-de-juridica-o-erro-que-mata-pequenos-negocios',
  '/blog/fator-r-simples-nacional-como-calcular',
  '/blog/holding-familiar-vale-a-pena-para-pequenos-empresarios',
  '/blog/reforma-tributaria-2026',
  '/blog/fale-conosco',
  '/blog/split-payment-reforma-tributaria-o-que-muda-para-sua-empresa',
  '/blog/contabilidade-industria-textil-blumenau-sc',
  '/blog/bloco-k-sped-fiscal-industria-guia',
  '/blog/abertura-de-empresa-em-santa-catarina-passo-a-passo-2026',
  '/blog/cnae-como-escolher-o-certo-e-por-que-errar-sai-caro',
  '/blog/simples-nacional-2026-tabelas-e-limites',
  '/blog/mei-2026-guia-completo-microempreendedor-individual',
  '/blog/desenquadramento-mei-por-faturamento-2026',
  '/blog/desenquadramento-mei-retroativo-2026',
  '/blog/desenquadramento-mei-excesso-receita-2026',
  '/blog/mei-estourou-o-faturamento-o-que-fazer-agora',
  '/blog/migrar-de-mei-para-ltda-guia-completo-2026',
  '/blog/desenquadramento-mei-retroativo-2026',
  '/blog/desenquadramento-mei-por-faturamento-2026',
  '/blog/desenquadramento-mei-excesso-receita-2026',
  '/blog/mei-estourou-o-faturamento-o-que-fazer-agora',
  '/blog/migrar-de-mei-para-ltda-guia-completo-2026',
  '/blog/guia-completo-para-abrir-empresa-em-blumenau',
  '/blog/reforma-tributaria-2026',
  '/blog/reforma-tributaria-2026',
  '/blog/fator-r-simples-nacional-contabilidade-ti',
  '/blog/lei-do-bem-empresas-tecnologia-inovacao'
];

const allReferenced = [...referencedBlogLinks, ...markdownReferenced];
const uniqueReferenced = [...new Set(allReferenced.map(l => l.replace('/blog/', '')))];

console.log('=== BROKEN BLOG LINKS ===');
for (const slug of uniqueReferenced) {
  if (!realBlogSlugs.includes(slug)) {
    console.log('BROKEN: /blog/' + slug);
  }
}

console.log('\n=== VALID BLOG LINKS ===');
for (const slug of uniqueReferenced) {
  if (realBlogSlugs.includes(slug)) {
    console.log('OK: /blog/' + slug);
  }
}